sparkpointio/sparkdefi-frontend

src/components/UnlockButton.tsx, src/views/Farms/components/DepositModal.tsx, src/views/Farms/components/FarmCard/CardHeading.tsx, src/views/Farms/components/FarmCard/FarmCard.tsx
=> style: Update farm cards and deposit modal

src/components/ModalInput/ModalInput.tsx, src/components/TokenPairImage/index.tsx, src/views/Pools/components/PoolCard/Modals/CollectModal.tsx, src/views/Pools/components/PoolCard/Modals/Stake.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx, src/views/Pools/components/PoolCard/index.tsx
Stake action modal (Fetch User Balance, Fetch Remaining stakable amount (pool limit minus total staked, Display pool limit, Change [Maximum stakable amount] to [Maximum stakable amount in this pool], ) )
Stake modal (Fetch actual value: Your Rate, Update line space, Remove 'Tokens' from your rate- staking modal)
Update token pair svg order
Disable Withdraw Component when user has no total staked
=> Pool components update

src/App.tsx, src/components/Menu/config.ts, src/hooks/useApprove.ts, src/hooks/useTokenBalance.ts, src/utils/callHelpers.ts, src/views/Farms/Redirects.tsx, src/views/Pools/components/PoolCard/CardActions/index.tsx, src/views/Pools/components/PoolCard/Modals/Stake.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx, src/views/Pools/components/PoolCard/index.tsx
=> Update pool UI and bug fixes

src/components/layout/Flex.tsx, src/views/Pools/index.tsx
=> Update Pools UI

package.json, src/components/layout/Flex.tsx, src/views/Pools/components/assets/pool-dark.svg, src/views/Pools/components/assets/pool-light.svg, src/views/Pools/index.tsx, yarn.lock
=> Add banner to pools page

src/components/Menu/config.ts, src/config/constants/pools.ts, src/views/Farms/Farms.tsx, src/views/Farms/components/assets/farm-dark.svg, src/views/Farms/components/assets/farm-light.svg, src/views/Pools/components/PoolTabButtons.tsx, src/views/Pools/index.tsx
Pools
- Add Switch Tab/ filter and search component
- Fix Upcoming tab rendering
Farms
- Redirect nav bar 'Farms' to '/farms'
- Merge farms banner from `add-banner-farms`
=> Add Pools filter and Merge Farms Banner 

src/views/Pools/index.tsx
- Adjusted header layout margins and added mobile responsiveness for pool controls container
=> Update header layout

src/views/Farms/Farms.tsx, src/views/Farms/components/DepositModal.tsx
Redirect Add More and Add Liquidity links to open in new tab
Align header image
=> Update staking modal links

src/views/Pools/index.tsx
=> Update Pools Card Layout

src/views/NotFound.tsx
=> Update Not Found Component

src/config/constants/meta.ts
Staking
- Pools | SparkPool - Earn SRK, SFUEL, and other tokens by just staking!
- Farms | SparkPool - Earn SRK, SFUEL, and other tokens by just staking!
=> Update page titles

src/config/constants/farms.ts, src/views/Farms/components/FarmCard/StakeAction.tsx
=> Add TIPSY-BNB Farm

src/config/constants/pools.ts
=> Add OWN-SFUEL pool

package.json, src/components/Menu/config.ts, yarn.lock
=> [SPSTK-2] Feat/update navbar

package.json, src/App.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx, src/views/Pools/components/PoolCard/Modals/Styled.tsx, yarn.lock
Problem:
Fix: 
Minor updates:
* Added redirection to pools when accessing '/'
=> [SPSTK-3] Fix modals drop down overlapping

package.json, yarn.lock
=> [SPSTK-4] Update sparkswap ui-kit to v1.2.2

package.json, src/components/PageHeader/PageHeader.tsx, src/views/Farms/Farms.tsx, src/views/Pools/index.tsx, yarn.lock
_Farms_
Before:
After:
_Pools_
Before:
After:
=> [SPSTK-7] [SPSTK-8] Reduce banner height and update sparkswap ui-kit version to 1.2.5

src/views/Farms/components/Divider.tsx, src/views/Pools/index.tsx
=> [SPSTK-10] Fix Pools HR width inconsistency

src/App.tsx, src/views/Farms/components/FarmCard/FarmCard.tsx
=> [SPSTK-13] Fix farms styled card width 

src/App.tsx
=> Add DeFi footer

src/App.tsx, src/views/Farms/components/FarmCard/FarmCard.tsx, src/views/Pools/components/PoolCard/index.tsx
=> [SPSTK-14] [SPSTK-15] Replace and convert remaining blocks to remaining days and make pool links distinctive 

src/config/constants/pools.ts
=> Add KGO-WBNB Staking Pool

src/config/constants/pools.ts
=> Add KGO-BTCB pool

src/components/Menu/config.ts
=> Update airdrop nav menu link

src/views/Farms/Farms.tsx, src/views/Farms/components/DepositModal.tsx, src/views/Farms/components/Modals/Stake.tsx, src/views/Farms/components/Modals/Styled.tsx, src/views/Farms/components/Styled.tsx, src/views/Farms/components/WithdrawModal.tsx, src/views/Pools/components/PoolCard/Modals/Stake.tsx, src/views/Pools/components/PoolCard/Modals/StakeModal.tsx, src/views/Pools/index.tsx
=> Fix responsiveness of farm and pool modals

src/views/Farms/Farms.tsx, src/views/Farms/components/Modals/Stake.tsx, src/views/Pools/index.tsx
=> Update Pools and farms header styles

package.json, src/utils/wallet.ts, src/utils/web3React.ts, yarn.lock
=> Resolve WC connector issues

src/App.tsx
=> Redirect to app.sparkswap.finance staking
